openapi: 3.0.0
info:
  title: Hotel Management System API
  description: Simple hotel booking API with user & hotel login, room CRUD, bookings, and check-in/check-out.
  version: 1.0.0

servers:
  - url: http://localhost:5000/api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        role:
          type: string
          enum:
            - user
            - owner
        phone:
          type: string
          maxLength: 10
        address:
          type: string
      required:
        - email
        - password
        - role
